source "https://rubygems.org"

gem "webrick"
gem "base64"
gem "bigdecimal"
gem "logger"
gem "wdm",">= 0.1.0"
gem "kramdown"
gem "kramdown-parser-gfm"
gem "rouge"
gem "jekyll", "~> 3.10.0"
gem "jekyll-paginate"
gem "jekyll-paginate-content"
gem "json"
gem "github-pages", group: :jekyll_plugins
